#!/usr/bin/env python3
"""Part H: API Routing and Workflow Repair."""
import json
import re
from pathlib import Path

BASE = Path("/home/ubuntu/ELYSIUM_CANON")
PATTERN_DIR = BASE / "07_YOS_PATTERN_LIBRARY"
DATE = "2026-06-27"

# Create required files
api_routing_protocol = f"""# API ROUTING PROTOCOL

**Date:** {DATE}
**Status:** CANONICAL

## 1. Principle
The engine claimed in documentation MUST match the actual API used. Falsifying engine provenance undermines the integrity of the yOS architecture.

## 2. Naming Conventions
- `Call ChatGPT via API.` (OpenAI endpoint)
- `Call Claude via API.` (Anthropic endpoint)
- `Call Gemini via API.` (Google endpoint)
- `Call Perplexity via API.` (Perplexity endpoint)

## 3. Fallback Protocol
If the primary engine fails (e.g., Anthropic 404), the fallback engine must be explicitly logged.
Example: `Requested: Claude 3.5 Sonnet. Executed: GPT-4o (Fallback due to API error).`

## 4. Provenance Metadata
Every document generated by the Program OS must include:
- `drafting_engine`
- `review_engine`
- `revision_engine`
- `orchestration_engine`
"""
(PATTERN_DIR / "API_ROUTING_PROTOCOL.md").write_text(api_routing_protocol)

api_call_log_schema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "call_id": {"type": "string"},
        "timestamp": {"type": "string", "format": "date-time"},
        "requested_engine": {"type": "string"},
        "executed_engine": {"type": "string"},
        "is_fallback": {"type": "boolean"},
        "task_type": {"type": "string", "enum": ["DRAFT", "REVIEW", "REVISION", "ORCHESTRATION"]},
        "target_document": {"type": "string"}
    },
    "required": ["call_id", "timestamp", "requested_engine", "executed_engine", "is_fallback", "task_type"]
}
(PATTERN_DIR / "API_CALL_LOG_SCHEMA.json").write_text(json.dumps(api_call_log_schema, indent=2))

model_routing_matrix = f"""# MODEL ROUTING MATRIX

**Date:** {DATE}

| Task Type | Primary Engine | Fallback 1 | Fallback 2 |
|---|---|---|---|
| Deep Research | Perplexity | Claude 3.5 Sonnet | GPT-4o |
| Ontology Structuring | Claude 3.5 Sonnet | GPT-4o | Gemini 1.5 Pro |
| Creative Drafting | GPT-4o | Claude 3.5 Sonnet | Gemini 1.5 Pro |
| Critical Review | Claude 3.5 Sonnet | GPT-4o | O1-preview |
| Code & Scripts | Claude 3.5 Sonnet | GPT-4o | O1-mini |
| Orchestration | Manus | - | - |
"""
(PATTERN_DIR / "MODEL_ROUTING_MATRIX.md").write_text(model_routing_matrix)
(PATTERN_DIR / "MODEL_ROUTING_MATRIX.json").write_text(json.dumps({
    "tasks": {
        "Deep Research": ["Perplexity", "Claude 3.5 Sonnet", "GPT-4o"],
        "Ontology Structuring": ["Claude 3.5 Sonnet", "GPT-4o", "Gemini 1.5 Pro"],
        "Creative Drafting": ["GPT-4o", "Claude 3.5 Sonnet", "Gemini 1.5 Pro"],
        "Critical Review": ["Claude 3.5 Sonnet", "GPT-4o", "O1-preview"],
        "Code & Scripts": ["Claude 3.5 Sonnet", "GPT-4o", "O1-mini"],
        "Orchestration": ["Manus"]
    }
}, indent=2))

# Audit existing scripts
scripts = list(BASE.glob("ELYSIUM/*.py"))
audit_results = []

for s in scripts:
    content = s.read_text(errors="ignore")
    
    # Check what it claims vs what it does
    claims_claude = "claude" in content.lower()
    uses_anthropic = "anthropic" in content.lower() or "openrouter" in content.lower()
    uses_openai = "openai" in content.lower()
    
    mismatch = False
    if claims_claude and not uses_anthropic and uses_openai:
        mismatch = True
    
    audit_results.append({
        "script": s.name,
        "purpose": "Multi-model generation" if "generate" in s.name else "Workflow/Audit",
        "claims_claude": claims_claude,
        "actual_api": "OpenAI" if uses_openai else ("Anthropic/OpenRouter" if uses_anthropic else "Unknown"),
        "mismatch": mismatch,
        "severity": "HIGH" if mismatch else "NONE",
        "repair": "Update script to use Anthropic SDK or explicitly log OpenAI fallback" if mismatch else "None"
    })

audit_md = f"""# MULTI-MODEL WORKFLOW AUDIT

**Date:** {DATE}

## Script Audit Table

| Script Name | Purpose | Claims Claude | Actual API | Mismatch | Severity | Required Repair |
|---|---|---|---|---|---|---|
"""
for r in audit_results:
    audit_md += f"| `{r['script']}` | {r['purpose']} | {'Yes' if r['claims_claude'] else 'No'} | {r['actual_api']} | {'**YES**' if r['mismatch'] else 'No'} | {r['severity']} | {r['repair']} |\n"

audit_md += """
## Action Taken
The API Routing Protocol has been established. Future scripts MUST explicitly log fallback execution and inject provenance metadata into generated documents.
"""
(PATTERN_DIR / "MULTI_MODEL_WORKFLOW_AUDIT.md").write_text(audit_md)

print("PART H COMPLETE ✓")
