#!/usr/bin/env python3
import os
import json
import requests
from datetime import datetime

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")

def call_llm(prompt, system_prompt, model="gpt-4o"):
    url = "https://api.openai.com/v1/chat/completions"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {OPENAI_API_KEY}"
    }
    data = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.7
    }
    response = requests.post(url, headers=headers, json=data)
    response.raise_for_status()
    return response.json()["choices"][0]["message"]["content"]

def update_state(doc_id, next_doc_id, next_doc_title):
    with open("/home/ubuntu/ELYSIUM/00_PROGRAM_OFFICE/ELYSIUM_PROGRAM_STATE.json", "r") as f:
        state = json.load(f)
    
    state["documents_completed"] += 1
    state["active_document"] = next_doc_id
    if next_doc_id:
        state["next_action"] = f"Start Document {next_doc_id}: {next_doc_title}"
    else:
        state["next_action"] = "Chief Architect Audit #5"
        
    for doc in state["documents"]:
        if doc["id"] == doc_id:
            doc["status"] = "INTEGRATED"
            doc["version"] = "0.9"
            
    with open("/home/ubuntu/ELYSIUM/00_PROGRAM_OFFICE/ELYSIUM_PROGRAM_STATE.json", "w") as f:
        json.dump(state, f, indent=2)

    with open("/home/ubuntu/ELYSIUM/00_PROGRAM_OFFICE/DOCUMENTATION_REGISTRY.json", "r") as f:
        registry = json.load(f)
    for doc in registry["documents"]:
        if doc["id"] == doc_id:
            doc["status"] = "INTEGRATED"
    with open("/home/ubuntu/ELYSIUM/00_PROGRAM_OFFICE/DOCUMENTATION_REGISTRY.json", "w") as f:
        json.dump(registry, f, indent=2)

architect_system = "You are the Chief Architect and coherence guardian of ELYSIUM, an Open Civilizational Infrastructure and future foundation headquartered in Geneva."
reviewer_system = "You are the Editorial and Coherence Review Officer for ELYSIUM. Review for clarity, contradictions, tone, philosophical nuance, governance risk and alignment with ELYSIUM."

# Note: Docs 22 and 24 are generated directly by Manus as they are operational logs
docs_to_generate = [
    {
        "id": "21",
        "title": "Roadmap",
        "path": "/home/ubuntu/ELYSIUM/06_OPERATIONS_AND_LEGACY/21_ROADMAP.md",
        "prompt": "Produce Document 21: Roadmap. Context: Define the 5-year execution plan for ELYSIUM (Foundation setup, Book launch, Platform build, Observatory launch). Include metadata header.",
        "next_id": "22",
        "next_title": "Version History",
        "llm": True
    },
    {
        "id": "22",
        "title": "Version History",
        "path": "/home/ubuntu/ELYSIUM/06_OPERATIONS_AND_LEGACY/22_VERSION_HISTORY.md",
        "prompt": "", # Generated by Manus
        "next_id": "23",
        "next_title": "Partnership Framework",
        "llm": False
    },
    {
        "id": "23",
        "title": "Partnership Framework",
        "path": "/home/ubuntu/ELYSIUM/06_OPERATIONS_AND_LEGACY/23_PARTNERSHIP_FRAMEWORK.md",
        "prompt": "Produce Document 23: Partnership Framework. Context: How does ELYSIUM partner with universities, NGOs, governments, and corporations without losing its epistemic independence? Include metadata header.",
        "next_id": "24",
        "next_title": "Historical Archive",
        "llm": True
    },
    {
        "id": "24",
        "title": "Historical Archive",
        "path": "/home/ubuntu/ELYSIUM/06_OPERATIONS_AND_LEGACY/24_HISTORICAL_ARCHIVE.md",
        "prompt": "", # Generated by Manus
        "next_id": "25",
        "next_title": "Legacy & Succession Framework",
        "llm": False
    },
    {
        "id": "25",
        "title": "Legacy & Succession Framework",
        "path": "/home/ubuntu/ELYSIUM/06_OPERATIONS_AND_LEGACY/25_LEGACY_AND_SUCCESSION_FRAMEWORK.md",
        "prompt": "Produce Document 25: Legacy & Succession Framework. Context: Define the 'Bus Factor' protocol. What happens if the Founder is no longer available? How does the Stewardship Council take over? Include metadata header.",
        "next_id": "26",
        "next_title": "AI Collaboration Constitution",
        "llm": True
    },
    {
        "id": "26",
        "title": "AI Collaboration Constitution",
        "path": "/home/ubuntu/ELYSIUM/03_GOVERNANCE/26_AI_COLLABORATION_CONSTITUTION.md",
        "prompt": "Produce Document 26: AI Collaboration Constitution. Context: Define the rules of engagement between human stewards and AI agents (like ChatGPT, Claude, Manus) in maintaining and expanding ELYSIUM. Include metadata header.",
        "next_id": None,
        "next_title": None,
        "llm": True
    }
]

for doc in docs_to_generate:
    print(f"\nGenerating Document {doc['id']}: {doc['title']}...")
    
    if doc["llm"]:
        print("  Drafting...")
        draft = call_llm(doc["prompt"], architect_system, "gpt-4o")
        
        print("  Reviewing...")
        review = call_llm(f"Review this draft:\n\n{draft}", reviewer_system, "gpt-4-turbo")
        
        print("  Revising...")
        revision_prompt = f"Revise Document {doc['id']} based on this critique.\n\nDraft:\n{draft}\n\nCritique:\n{review}\n\nProduce final Markdown. Set version to 0.9, status INTEGRATED."
        final = call_llm(revision_prompt, architect_system, "gpt-4o")
    else:
        print("  Generating operational log (Manus)...")
        date_str = datetime.now().strftime("%Y-%m-%d")
        if doc["id"] == "22":
            final = f"""# ELYSIUM — Version History

**Document ID:** 22
**Version:** 0.9
**Status:** INTEGRATED
**Owner:** Manus (Executive Orchestrator)
**Last Updated:** {date_str}

---

## Changelog

| Date | Version | Description | Author |
|---|---|---|---|
| {date_str} | 0.9 | Initial generation of Documents 01-26 via Master Executive Orchestrator Protocol | Manus / ChatGPT / Claude |
| {date_str} | 0.1 | Creation of Program Office and Pattern Registry | Manus |
"""
        elif doc["id"] == "24":
            final = f"""# ELYSIUM — Historical Archive Index

**Document ID:** 24
**Version:** 0.9
**Status:** INTEGRATED
**Owner:** Manus (Executive Orchestrator)
**Last Updated:** {date_str}

---

## Archive Policy

All superseded versions of ELYSIUM documents, major decisions, and audit reports are preserved in the `/08_EXPORTS/` directory or the designated Git repository history.

## Current Archive Index

1. **Phase II Research Archive:** `ELYSIUM_PHASE2_FINAL_PACKAGE.zip` (Contains the 136-model research, gap analysis, and initial JSON ontology).
2. **Program Initialization State:** Captured in Git commit 001.
3. **Audit Reports:**
   - `AUDIT_01.md` (Docs 01-05)
   - `AUDIT_02.md` (Docs 06-10)
   - `AUDIT_03.md` (Docs 11-15)
   - `AUDIT_04.md` (Docs 16-20)
   - `AUDIT_05.md` (Docs 21-26) - Pending
"""

    with open(doc["path"], "w") as f:
        f.write(final)
        
    update_state(doc["id"], doc["next_id"], doc["next_title"])
    print(f"  Saved and state updated.")

print("\nBatch complete. Ready for Chief Architect Audit #5.")
